### POST Correcte
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content":"Una nota IMPORTANT",
    "important":true
}

### Content missing #1

POST http://localhost:3001/api/notes 
Content-Type: application/json

{}

### Content missing #2

POST http://localhost:3001/api/notes
Content-Type: application/json

{ "title": ""}


### Empty String
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content":"",
    "important":true
}
