PUT http://localhost:3001/api/notes/69961ea7f15b737c27dcb2a8
Content-Type: application/json

{
    "content":"Nota actualizada2 subscribete",
    "important":true
}


### Malformed id
PUT http://localhost:3001/api/notes/6984857d2c724bf453dc335 
Content-Type: application/json

{
    "content":"Nota actualizada subscribete",
    "important":true
}
### Id not found

PUT http://localhost:3001/api/notes/6984857d2c724bf453dc3357 
Content-Type: application/json

{
    "content":"Nota actualizada subscribete",
    "important":true
}












